### ISSUE TITLE
not getting login email

### ISSUE THREAD

**Issue by ChipNowacek** [ibgib/ibgib#201]
When I fill this out:
![screen shot 2017-04-28 at 10 24 05 am](https://cloud.githubusercontent.com/assets/3668197/25532901/da1bda6e-2bfc-11e7-8f63-4505d35cf891.png)
Am I supposed to get something at that email address?

**Comment by bill-mybiz** [comment]
Yes. Mailgun can be iffy the first time. I need to have a prompt or confirmation dialog when the email is sent for sure. I can check mailgun logs to see if they sent it to be sure. Give me a little bit here and I'll check. 

Also it won't hurt if you try again, but usually it's just a mailgun server thing. Once you're logged in, it lasts for thirty days tho.

**Comment by ChipNowacek** [comment]
I've tried twice so far. I'll try again.

**Comment by bill-mybiz** [comment]
Checking the logs, it's saying that the domain wasn't found.

**Comment by ChipNowacek** [comment]
Hmm. The address works. Is Mailgun checking for something other than <string>@<subdomain>.<tld> structure or something?

**Comment by bill-mybiz** [comment]
> Is Mailgun checking for something other than @. structure or something?

Do you mean is it doing more than checking your mx record for ownership? I think they have more security measures in place to avoid sending spam, etc. 

Here is a good link on mailgun's security improvements:

http://blog.mailgun.com/outgoing-message-security-settings-now-available-in-the-control-panel/

**Comment by ChipNowacek** [comment]
I guess I simply don't know what:

> the domain wasn't found

means. Should I use another address?

**Comment by bill-mybiz** [comment]
That might be good as a temporary workaround. 

One of the interesting aspects of ibGib is that it's supposed to handle collaboration more gracefully. This also means in effect if you get one or more of your email accounts (or other identities when those are implemented) compromised, you can "collaborate with yourself", since the data is not deleted. Some of the conveniences of this are not implemented yet though, such as importing/transporting entire ibGib graphs, and automatically forking and working with the forks when trying to edit others' ibGibs (even when that "other" identity is your other email address).

But this is certainly one of the experimental aspects of ibGib's architecture!

**Comment by bill-mybiz** [comment]
Hah, I didn't mention my point there...my point is that whatever email you use now, ideally you should be able to transition to another (and additional emails) with little friction.

**Comment by ChipNowacek** [comment]
No worries. I'm trying a straight gmail.com address.

**Comment by ChipNowacek** [comment]
No joy yet on the gmail.com-based address.

**Comment by bill-mybiz** [comment]
> No worries. I'm trying a straight gmail.com address.

Were you able to log in with the gmail account? Ah, I see (I was typing this when that response came in):

> No joy yet on the gmail.com-based address.

The logs show it as having gone through, but that isn't always a good indicator. I really apologize for the inconvenience! You're literally the first person that has expressed any actual interest in the technology, which I suppose shouldn't be surprising since you're an ontology personage. It has worked for the existing email addresses that we've tried, especially since I had them change the server that they were sending from (it had a low sending score, and thus was getting delayed).

> I just hope hackers find stripping the address from ibGib difficult.

What do you mean by this? If you are concerned with your email address becoming public, then ibGib definitely isn't the right tool - not ibGib the website anyway. The website is designed specifically to have public identities visible. All ibGib are publicly available via the json api, i.e. if they have the `ib^gib` (the content address), then they have the content address of all dependency ibGibs, and they can get it from the website.

The ibGib technology can be localized as a data backing store, but if you are wanting compartmentalization, then you're basically losing a primary benefit of the approach.

**Comment by bill-mybiz** [comment]
Here is a link on information about the error that I'm seeing in the logs:

http://stackoverflow.com/questions/27930771/mailgun-messages-from-subdomain-without-mx-record-get-rejected-by-some-mail-prov

Apparently it is a mailgun issue, and it looks like more of a reason to drop them and use someone else. :frowning_face:

**Comment by ChipNowacek** [comment]
> I really apologize for the inconvenience!

No problem. I just don't know what to do.

> What do you mean by this? If you are concerned with your email address becoming public, then ibGib definitely isn't the right tool - not ibGib the website anyway. The website is designed specifically to have public identities visible. All ibGib are publicly available via the json api, i.e. if they have the ib^gib (the content address), then they have the content address of all dependency ibGibs, and they can get it from the website.

> The ibGib technology can be localized as a data backing store, but if you are wanting compartmentalization, then you're basically losing a primary benefit of the approach.

Loud and clear, I've heard what you said about privacy. I'm open to open. It's just that people take advantage. That's all. I submitted my email address knowing it would be available. I've just been hacked so many times that I feel violated.

**Comment by ChipNowacek** [comment]
While I may have an infinite number of cheeks to turn, I don't have access to all of them just yet.

**Comment by ChipNowacek** [comment]
I don't know diddly about Mailgun. I'm sorry it's giving your trouble. It's more of a headache for you than me — and I still want to play with ibGib as fully as possible. Is image posting the only thing I can't get to?

**Comment by bill-mybiz** [comment]
> Loud and clear, I've heard what you said about privacy. I'm open to open. 

Sorry if I'm beating a dead :horse:, I just am not sure of what you've read, etc. :smile:

> It's just that people take advantage. That's all. I submitted my email address knowing it would be available. I've just been hacked so many times that I feel violated.

This is a complicated subject, and it's totally up to you as to how comfortable you are with what level of privacy you require. ibGib is not about removing privacy, but rather it is about focusing on the benefits of collaboration. 

I see everyone getting hacked non-stop, and the thing is that data analytics are already being collected extensively. People just don't have access to their own analytics, the existing analytics are compartmentalized, and it's expensive in terms of complexity to combine silos. 

> I don't know diddly about Mailgun. I'm sorry it's giving your trouble. It's more of a headache for you than me — and I still want to play with ibGib as fully as possible. Is image posting the only thing I can't get to?

The notifications won't work, but since those are still a WIP anyway it's not a huge loss. (They're slow and passive, somewhat hidden).

**Comment by bill-mybiz** [comment]
For example, if you were to create an ibGib "anonymously" (with just the session identity), then you send me a link, I could then reply to you on that ibGib.

I'm working on implementing a more friendly chat mechanism, but I'm trying to get some Amazon Echo stuff done before focusing back on ibGib.

**Comment by ChipNowacek** [comment]
I didn't mean to sound impatient. I know you want to be upfront. Admirable really.

**Comment by ChipNowacek** [comment]
I saw the Echo stuff. It's cool.

**Comment by bill-mybiz** [comment]
Thanks! I'm thinking that the askGib (alexa skills kit) library might actually be useful to someone who is looking for a bit more compile-time verification with TS. The working branch is [here](https://github.com/ibgib/askGib/tree/issue_1_update). Fun stuff.

What is your ontological code focused on? Business, school work, ...?

**Comment by bill-mybiz** [comment]
I had this problem, and adding "noreply-login@ibgib.com" to contacts fixed the issue.

**Comment by OvermindDL1** [comment]
If you setup proper mail authentication records on your DNS then it should fix that issue as well without the end-user needing to do anything.  It is quite a big pain, but only needs to be done once.  Google has instructions for webmasters on how to do it (literally in Google's help, not just via a search).

**Comment by bill-mybiz** [comment]
Hey @OvermindDL1 !

I thought the same thing, that it was a misconfiguration on my dns, but to the best of my knowledge I have configured my dns to work with mailgun. The problem seems to come from the fact that I'm on the free tier servers,  which associates my emails with possible spam. So I can either pay for better servers,  which ain't a possibility,  or this workaround. Anything further is unfortunately beyond my abilities atm. :-/

**Comment by OvermindDL1** [comment]
You said you are using mailgun, is that a secondary service or are you sending it via gmail itself?  For note, your spf record is:

```dns
ibgib.com.              400 IN TXT "v=spf1 include:_spf.google.com ~all"
```

So you *only* allow email for your domain to be send from google's server, no one else's.  https://support.google.com/a/answer/33786

Also, are you signing your messages?  http://www.dkim.org/

Also you do not seem to have DMARC setup (but depending on how you send it then it may not be necessary, if using a third-party service then you probably need this).  https://dmarc.org/

Like I said, the world of email sending is a pain.  ^.^;

**Comment by bill-mybiz** [comment]
Secondary service, which from your info looKS lIke they useem google. It's very possible that future investment in advanced config with them is possible.  I just can't do it unfortunately. Iirc I looked into both dkim and dmarc and did what was available to me. 

> Like I said, the world of email sending is a pain. ^.^;

Yeah, it's very complicated! I'll keep your thoughts in mind if/when I'm able to revisit this. At least for now there is a workaround.
